export const toolCatalog = [
  {
    "slug": "number-base",
    "name": "Number Base Converter",
    "category": "Developer",
    "tags": [
      "Binary",
      "Hex",
      "BigInt"
    ],
    "description": "Convert integers exactly between bases 2\u201336, even beyond the safe integer range.",
    "implementation": "shared"
  },
  {
    "slug": "json-string",
    "name": "JSON String Escaper",
    "category": "Developer",
    "tags": [
      "Escape",
      "Unescape",
      "Unicode"
    ],
    "description": "Escape plain text as a JSON string or restore a quoted JSON string to readable text.",
    "implementation": "shared"
  },
  {
    "slug": "utm-builder",
    "name": "UTM Link Builder",
    "category": "Web",
    "tags": [
      "Campaign",
      "URL",
      "Marketing"
    ],
    "description": "Build campaign URLs with encoded UTM parameters while preserving existing query values.",
    "implementation": "shared"
  },
  {
    slug: "json-fix",
    name: "JSON Fix",
    category: "Developer",
    tags: ["Repair", "Format", "Validate"],
    description: "Repair malformed JSON and turn it into clean, readable data.",
    implementation: "existing",
  },
  {
    slug: "json-diff",
    name: "JSON Diff",
    category: "Developer",
    tags: ["Compare", "Objects", "Paths"],
    description: "Compare two JSON documents and inspect added, removed, and changed values.",
    implementation: "shared",
  },
  {
    slug: "timestamp",
    name: "Timestamp Converter",
    category: "Developer",
    tags: ["Unix", "ISO 8601", "Time"],
    description: "Convert Unix timestamps and local dates while keeping an eye on the current time.",
    implementation: "shared",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    category: "Developer",
    tags: ["Token", "Claims", "Local"],
    description: "Decode JWT headers and payloads locally without sending tokens to a server.",
    implementation: "shared",
  },
  {
    slug: "base64",
    name: "Base64 Encoder",
    category: "Developer",
    tags: ["Encode", "Decode", "UTF-8"],
    description: "Encode or decode UTF-8 text with standard and URL-safe Base64.",
    implementation: "shared",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    category: "Developer",
    tags: ["Pattern", "Matches", "Groups"],
    description: "Test regular expressions, inspect capture groups, and highlight every match.",
    implementation: "shared",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    category: "Developer",
    tags: ["UUID v4", "Generate", "Validate"],
    description: "Generate secure UUID v4 values in batches and validate existing UUIDs.",
    implementation: "shared",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    category: "Developer",
    tags: ["SHA-256", "Files", "Digest"],
    description: "Calculate SHA-256, SHA-384, or SHA-512 hashes for text and local files.",
    implementation: "shared",
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    category: "Developer",
    tags: ["XML", "Format", "Validate"],
    description: "Validate, format, or minify XML while keeping the document in your browser.",
    implementation: "shared",
  },
  {
    slug: "cron-inspector",
    name: "Cron Expression Inspector",
    category: "Developer",
    tags: ["Cron", "Schedule", "Timezone"],
    description: "Validate five-field cron expressions and preview upcoming local run times.",
    implementation: "shared",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    category: "Developer",
    tags: ["Password", "Random", "Local"],
    description: "Generate configurable passwords with cryptographically secure browser randomness.",
    implementation: "shared",
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    category: "Developer",
    tags: ["Dates", "Duration", "Business days"],
    description: "Measure calendar spans and add or subtract days, weeks, months, or years.",
    implementation: "shared",
  },
  {
    slug: "text-clean",
    name: "Text Clean",
    category: "Text",
    tags: ["Formatting", "Whitespace", "Copy"],
    description: "Remove copied rich-text and AI formatting while preserving readable structure.",
    implementation: "existing",
  },
  {
    slug: "text-diff",
    name: "Text Diff",
    category: "Text",
    tags: ["Compare", "Lines", "Changes"],
    description: "Compare text line by line with a clear view of additions and removals.",
    implementation: "shared",
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    category: "Text",
    tags: ["camelCase", "Title Case", "snake_case"],
    description: "Switch text between common writing and programming case styles.",
    implementation: "shared",
  },
  {
    slug: "line-processor",
    name: "Line Processor",
    category: "Text",
    tags: ["Sort", "Deduplicate", "Trim"],
    description: "Clean, sort, reverse, number, prefix, or deduplicate lists of lines.",
    implementation: "shared",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    category: "Text",
    tags: ["Words", "Reading Time", "Frequency"],
    description: "Measure words, characters, sentences, lines, reading time, and common terms.",
    implementation: "shared",
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    category: "Text",
    tags: ["Markdown", "Preview", "Safe HTML"],
    description: "Preview a practical Markdown subset without executing pasted HTML or scripts.",
    implementation: "shared",
  },
  {
    slug: "color-spectrum",
    name: "Color Spectrum",
    category: "Image",
    tags: ["Palette", "Pixels", "Export"],
    description: "Extract dominant colors, inspect pixels, and export palettes from an image.",
    implementation: "existing",
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    category: "Image",
    tags: ["Compress", "JPEG", "WebP"],
    description: "Reduce image file size locally with an adjustable quality setting.",
    implementation: "shared",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    category: "Image",
    tags: ["Dimensions", "Scale", "Canvas"],
    description: "Resize images to exact dimensions while optionally preserving aspect ratio.",
    implementation: "shared",
  },
  {
    slug: "image-converter",
    name: "Image Format Converter",
    category: "Image",
    tags: ["PNG", "JPEG", "WebP"],
    description: "Convert images between PNG, JPEG, and WebP entirely in the browser.",
    implementation: "shared",
  },
  {
    slug: "contrast-checker",
    name: "Color Contrast Checker",
    category: "Image",
    tags: ["WCAG", "Accessibility", "Color"],
    description: "Check foreground and background colors against WCAG contrast targets.",
    implementation: "shared",
  },
  {
    slug: "metadata-remover",
    name: "Image Metadata Remover",
    category: "Image",
    tags: ["Privacy", "EXIF", "Local"],
    description: "Strip EXIF and other metadata by safely re-encoding an image locally.",
    implementation: "shared",
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    category: "Web",
    tags: ["URL", "Query", "Inspect"],
    description: "Break an absolute URL into its origin, path, query parameters, and fragment.",
    implementation: "shared",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder",
    category: "Web",
    tags: ["Encode", "Decode", "Percent"],
    description: "Encode or decode URL components without sending addresses to a remote service.",
    implementation: "shared",
  },
  {
    slug: "csv-json-converter",
    name: "CSV ↔ JSON Converter",
    category: "Web",
    tags: ["CSV", "JSON", "Data"],
    description: "Convert quoted CSV records and JSON object arrays in either direction locally.",
    implementation: "shared",
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    category: "Web",
    tags: ["HTML", "Entities", "Escape"],
    description: "Encode HTML-sensitive characters or decode named and numeric character references.",
    implementation: "shared",
  },
  {
    slug: "css-unit-converter",
    name: "CSS Unit Converter",
    category: "Web",
    tags: ["CSS", "rem", "Viewport"],
    description: "Compare px, rem, em, vw, and vh values using explicit layout assumptions.",
    implementation: "shared",
  },
];

export const categoryOrder = ["Developer", "Text", "Image", "Web"];
