export const toolEditorial = {
  "json-fix": {
    scenarios: [
      { title: "Configuration recovery", text: "Repair a copied settings fragment with unquoted keys, single-quoted strings, or trailing commas before placing it back in a project." },
      { title: "API debugging", text: "Turn an almost-JSON response from a log, ticket, or chat message into a parseable document that can be inspected and compared." },
      { title: "Data handoff", text: "Normalize a small sample supplied by another team so both sides can discuss the same formatted structure and property paths." },
    ],
    review: "Compare the repaired document with the source line by line. Pay special attention to inferred quotes, missing separators, numbers with leading zeroes, and places where truncated data could have more than one reasonable meaning.",
    alternative: "Use a schema validator after the syntax is repaired when field names, required properties, types, or allowed values matter. Use JSON Diff when both documents already parse and the task is to explain what changed.",
    privacy: "Repair happens in the active tab. That reduces network exposure, but clipboard managers, browser extensions, shared devices, and screen recording can still expose secrets.",
    checklist: ["Keep the original input until the result is verified.", "Confirm every inferred string and value.", "Validate against the application schema.", "Rotate any production secret pasted on an untrusted device."],
    relatedGuides: ["repair-invalid-json"],
  },
  "json-diff": {
    scenarios: [
      { title: "Release comparison", text: "Compare configuration snapshots before and after a deployment to locate the exact property paths that were added, removed, or changed." },
      { title: "API contract review", text: "Inspect two response examples when a consumer reports a regression and distinguish value changes from harmless formatting or key reordering." },
      { title: "Fixture maintenance", text: "Review updated test fixtures without reading two large nested objects side by side or relying on line wrapping in an editor." },
    ],
    review: "Interpret array changes carefully because the comparison is index-based. One inserted element can make several later entries appear changed even when their values only moved to a new position.",
    alternative: "Use a source-control diff for files where comments, whitespace, or key order are meaningful. Use a semantic patch format when the differences must be applied automatically rather than reviewed by a person.",
    privacy: "Both documents remain in browser memory. Clear the editors before sharing the screen or leaving a managed workstation, especially when payloads contain account identifiers or internal URLs.",
    checklist: ["Confirm both inputs are valid JSON.", "Separate reordering from value changes.", "Review added and removed paths first.", "Do not treat a clean diff as schema validation."],
    relatedGuides: ["repair-invalid-json"],
  },
  timestamp: {
    scenarios: [
      { title: "Log investigation", text: "Translate an event timestamp from an application log into UTC and local time so it can be compared with alerts and user reports." },
      { title: "API integration", text: "Check whether an endpoint expects Unix seconds, Unix milliseconds, or an ISO 8601 string before sending a scheduled value." },
      { title: "Expiry review", text: "Inspect token, cache, or job expiry values and calculate whether the displayed time difference is caused by timezone presentation." },
    ],
    review: "Verify the unit before trusting a numeric result. A seconds value interpreted as milliseconds lands near 1970, while a milliseconds value interpreted as seconds can exceed the browser date range.",
    alternative: "Use a timezone-aware date library when recurring schedules, daylight-saving transitions, calendar arithmetic, or historical regional rules affect business behavior. This converter is intended for inspection, not scheduling policy.",
    privacy: "Dates are parsed locally and normally contain little sensitive data, but timestamps combined with user identifiers can still reveal activity patterns in screenshots or copied reports.",
    checklist: ["Identify seconds versus milliseconds.", "Compare UTC and device-local output.", "Include an explicit offset in shared dates.", "Test daylight-saving boundaries separately."],
    relatedGuides: ["timestamps-and-timezones"],
  },
  "jwt-decoder": {
    scenarios: [
      { title: "Claim inspection", text: "Read issuer, audience, subject, role, and expiry claims while debugging why an application accepts or rejects a session." },
      { title: "Environment checks", text: "Compare tokens from staging and production to spot a wrong audience, tenant, scope, or authorization-server URL." },
      { title: "Support diagnostics", text: "Explain the non-secret structure of a redacted sample without installing a command-line decoder or sending it to a third-party service." },
    ],
    review: "Treat every decoded field as untrusted text until the signature and application rules are verified. Also check expiry, not-before, issuer, audience, token type, and any server-side revocation policy.",
    alternative: "Use the authentication library in the target application for real verification because it has the expected algorithm, key set, issuer, and audience. A browser decoder cannot make an authorization decision.",
    privacy: "Decoding is local, but an active bearer token may grant access to an account. Prefer an expired or redacted token and never publish the full value in an issue, chat, or screenshot.",
    checklist: ["Decode is not verification.", "Check issuer and audience together.", "Review exp and nbf as UTC times.", "Revoke a token exposed outside a trusted device."],
    relatedGuides: ["jwt-decode-vs-verify", "base64-is-not-encryption"],
  },
  base64: {
    scenarios: [
      { title: "Configuration inspection", text: "Decode a Base64 environment value to confirm its text and encoding before moving it between deployment systems." },
      { title: "Protocol debugging", text: "Inspect a small encoded field in an HTTP header, JSON document, or URL-safe token without confusing transport encoding with protection." },
      { title: "UTF-8 verification", text: "Check that accented letters and non-Latin text survive an encode-and-decode round trip as the expected Unicode characters." },
    ],
    review: "Look for the correct alphabet and padding rules. Standard Base64 uses plus and slash, while Base64URL uses hyphen and underscore; copied values may omit the final equals signs.",
    alternative: "Use encryption when confidentiality is required, a cryptographic signature when authenticity matters, and a hash when comparing integrity. Base64 only represents bytes as text-safe characters.",
    privacy: "Conversion runs locally, but the decoded result may reveal credentials or personal data that looked harmless while encoded. Handle the readable output according to its real sensitivity.",
    checklist: ["Choose standard or URL-safe alphabet.", "Preserve UTF-8 when text is expected.", "Do not describe Base64 as encryption.", "Avoid placing secrets in URLs or public logs."],
    relatedGuides: ["base64-is-not-encryption", "jwt-decode-vs-verify"],
  },
  "regex-tester": {
    scenarios: [
      { title: "Input validation", text: "Develop a bounded pattern for identifiers, filenames, or form fields using representative valid and invalid examples." },
      { title: "Log extraction", text: "Test capture groups for dates, request IDs, or status values before applying a pattern in a script or observability query." },
      { title: "Text cleanup", text: "Preview every match in copied content before replacing it elsewhere, reducing the chance of deleting a wider region than intended." },
    ],
    review: "Test empty strings, long lines, unexpected Unicode, newline boundaries, and near-matches. Confirm whether the pattern is anchored and whether global, multiline, case-insensitive, or Unicode flags change the result.",
    alternative: "Use a parser for nested or grammar-based formats such as HTML, JSON, programming languages, and complex addresses. A regular expression is most reliable for well-bounded lexical patterns.",
    privacy: "The pattern and sample stay in the tab. Replace production names, email addresses, tokens, and log payloads with realistic synthetic examples before sharing a test case.",
    checklist: ["Include positive and negative samples.", "Inspect every capture group.", "Test long adversarial input.", "Confirm syntax in the destination regex engine."],
    relatedGuides: ["regex-testing-safely"],
  },
  "uuid-generator": {
    scenarios: [
      { title: "Test fixtures", text: "Create independent identifiers for sample records so tests do not accidentally depend on a production sequence or database connection." },
      { title: "Client-side drafts", text: "Assign temporary IDs to offline items before synchronization while keeping collision probability acceptably small." },
      { title: "Format validation", text: "Check whether a received identifier follows the canonical UUID shape and carries the version and variant bits expected by an integration." },
    ],
    review: "Confirm whether the receiving system expects canonical lowercase text, uppercase text, braces, or a compact form. Validation of shape does not confirm ownership, database existence, or authorization.",
    alternative: "Use an ordered identifier such as UUID v7 or a database-generated key when index locality, sort order, or creation-time information is important. This tool generates random UUID v4 values only.",
    privacy: "Generation does not use a server and UUIDs are not derived from personal data. Nevertheless, an identifier copied from a real system can still act as a lookup key and should be handled accordingly.",
    checklist: ["Confirm UUID v4 is the required version.", "Keep canonical hyphenation when possible.", "Do not use an ID as an access secret.", "Enforce uniqueness in persistent storage."],
    relatedGuides: [],
  },
  "hash-generator": {
    scenarios: [
      { title: "Download integrity", text: "Hash a downloaded file and compare the complete digest with a value published through a trusted channel." },
      { title: "Build reproducibility", text: "Compare artifacts from two environments to determine whether their bytes are identical before investigating semantic differences." },
      { title: "Text diagnostics", text: "Reveal invisible differences caused by line endings, encoding, normalization, or trailing whitespace when text looks identical on screen." },
    ],
    review: "Compare the algorithm and every hexadecimal character. A digest copied from the same compromised server as the file does not provide an independent authenticity guarantee.",
    alternative: "Use a digital signature when the publisher's identity must be verified and a password-hashing algorithm with a salt and work factor for stored passwords. General SHA digests are not sufficient for either task.",
    privacy: "Files are read through browser APIs and hashed locally. The digest can still reveal that a file matches a known document, so avoid publishing hashes of sensitive, predictable material.",
    checklist: ["Match the expected SHA algorithm.", "Trust the source of the reference digest.", "Compare the full value, not a prefix.", "Use dedicated password hashing for credentials."],
    relatedGuides: [],
  },
  "xml-formatter": {
    scenarios: [
      { title: "API payload diagnosis", text: "Format a compact SOAP, RSS, Atom, sitemap, or custom XML response to find the element where nesting or namespaces differ from the receiving contract." },
      { title: "Configuration review", text: "Validate a small application or build configuration before committing it, while keeping credentials and internal hostnames on the device." },
      { title: "Source comparison", text: "Normalize two short XML fragments into a readable shape before comparing their structural differences in a text diff." },
    ],
    review: "Inspect the XML declaration, root element, namespace prefixes, attribute values, entity references, comments, CDATA, and whitespace-sensitive text. A successful parse proves only that elements and syntax are well formed.",
    alternative: "Use an XSD-aware validator, application test suite, or specialized editor when schema rules, external entities, XPath, canonicalization, signatures, or very large streaming documents matter.",
    privacy: "Source and result remain in the browser tab. XML commonly contains credentials, internal URLs, customer identifiers, and signed data, so use synthetic samples in public issues and avoid formatting active secrets on an untrusted device.",
    checklist: ["Confirm one root document is present.", "Validate against the real schema separately.", "Review mixed-content whitespace.", "Do not reformat signed XML casually."],
    relatedGuides: [],
  },
  "cron-inspector": {
    scenarios: [
      { title: "Deployment review", text: "Check a scheduled backup, report, cleanup, or integration expression before adding it to a server, container, CI workflow, or cloud scheduler." },
      { title: "Timezone incident", text: "Compare expected wall-clock times with the device timezone when a job appears an hour early, an hour late, duplicated, or missing." },
      { title: "Dialect migration", text: "Identify unsupported seconds, year, question-mark, last-day, weekday, or macro syntax while moving a schedule between platforms." },
    ],
    review: "Record the exact cron dialect, timezone, daylight-saving policy, concurrency behavior, retry policy, and what happens after downtime. Preview both ordinary dates and the next timezone transition when local civil time is involved.",
    alternative: "Use the scheduler's own validator and execution history for production confirmation. Event queues, durable workflows, or application-level scheduling are better when every run must be guaranteed, retried, deduplicated, or audited.",
    privacy: "The expression is parsed locally and usually contains no secret. Job timing can still reveal internal operational routines, maintenance windows, reporting cycles, or backup policy when shared publicly.",
    checklist: ["Confirm five-field order.", "Match the production timezone.", "Check DOM/DOW semantics.", "Test daylight-saving and missed-run behavior."],
    relatedGuides: ["cron-schedules-and-timezones", "timestamps-and-timezones"],
  },
  "password-generator": {
    scenarios: [
      { title: "Password-manager entry", text: "Create a unique high-entropy password for an account whose registration form cannot invoke the password manager's built-in generator." },
      { title: "Legacy composition rules", text: "Satisfy a documented requirement for uppercase, lowercase, numbers, or symbols without replacing secure randomness with a predictable personal pattern." },
      { title: "Temporary credential", text: "Generate a one-time initial secret that must be transferred through an approved channel and changed by the recipient at first use." },
    ],
    review: "Prefer the longest value the service accepts, keep every account unique, verify that copying did not add spaces, and store the result before closing the page. Do not send passwords through ordinary email or public chat.",
    alternative: "Use the generator built into a reputable password manager whenever possible because it can create, fill, store, synchronize, and audit the credential without exposing it through an extra clipboard step. Use passkeys when the service supports them.",
    privacy: "Generation is local and the site does not retain a password history. Browser extensions, clipboard managers, screen capture, device malware, and people nearby remain outside the page's control, so generate only on a trusted device.",
    checklist: ["Use a unique value per account.", "Prefer a password manager or passkey.", "Match the site's maximum length.", "Clear exposed clipboard history."],
    relatedGuides: [],
  },
  "date-calculator": {
    scenarios: [
      { title: "Project planning", text: "Measure calendar and weekday spans between milestones before applying an organization's holiday calendar and working-hour policy." },
      { title: "Renewal and expiry", text: "Add a documented number of days, months, or years to a start date and inspect how month-end clamping changes the result." },
      { title: "Editorial timeline", text: "Count inclusive calendar dates for a campaign or event while keeping that convention explicit for collaborators." },
    ],
    review: "Decide whether the rule uses elapsed days, inclusive dates, weekdays, business days, calendar months, or fixed-hour durations. Test leap years, month ends, reverse order, and jurisdiction-specific holidays.",
    alternative: "Use a domain-specific calendar library or authoritative system for legal deadlines, financial day-count conventions, trading calendars, payroll, holidays, and timezone-aware timestamps. This page performs transparent general calendar arithmetic.",
    privacy: "Date-only values are processed locally. Dates associated with medical events, employment, travel, contracts, or customer records can still be personal information when exposed in screenshots or reports.",
    checklist: ["Name the counting convention.", "Check month-end clamping.", "Apply official holidays separately.", "Use timestamp tools for time-of-day work."],
    relatedGuides: ["cron-schedules-and-timezones", "timestamps-and-timezones"],
  },
  "text-clean": {
    scenarios: [
      { title: "Document handoff", text: "Remove copied styling and repeated blank lines before moving chat or document text into an email, CMS, or plain-text field." },
      { title: "Prompt preparation", text: "Normalize accidental formatting in a collected prompt while preserving paragraph boundaries that carry meaning." },
      { title: "Spreadsheet cleanup", text: "Reduce stray whitespace and rich-text artifacts before placing one cleaned block into a cell or splitting it into rows." },
    ],
    review: "Read headings, numbered steps, quotations, and code blocks after cleaning. Whitespace can be meaningful, and automatic cleanup cannot know whether an indentation level or repeated blank line was intentional.",
    alternative: "Use a full Markdown parser when the goal is to preserve and render Markdown semantics. Use find-and-replace or a line processor when only one precisely defined transformation is required.",
    privacy: "Cleanup is performed in the page. Copied text may still be retained by the operating system clipboard or browser extensions, so use a managed workflow for confidential documents.",
    checklist: ["Keep a copy of the original.", "Review lists and code indentation.", "Check paragraph boundaries after cleanup.", "Clear confidential text when finished."],
    relatedGuides: [],
  },
  "text-diff": {
    scenarios: [
      { title: "Editorial revision", text: "Compare two drafts to see which complete lines were inserted or removed before accepting a rewritten section." },
      { title: "Generated output", text: "Check whether a template, prompt, or export changed across runs without committing temporary files to source control." },
      { title: "Configuration notes", text: "Review small plain-text settings or lists where line order matters and a structured JSON comparison is not appropriate." },
    ],
    review: "A line-level diff can make a small edit look like one removed line and one added line. Inspect neighboring lines and intentional reordering before concluding that content was deleted.",
    alternative: "Use JSON Diff for structured objects, a word-level editor for prose collaboration, and source control for project history, authorship, merging, and reproducible review.",
    privacy: "Both versions remain in memory in the tab. Replace customer data and credentials with synthetic content before using a comparison in a public demonstration or issue report.",
    checklist: ["Confirm which side is original.", "Choose whitespace behavior deliberately.", "Review moved lines separately.", "Save important history in source control."],
    relatedGuides: [],
  },
  "case-converter": {
    scenarios: [
      { title: "API naming", text: "Convert a readable label into camelCase or snake_case while designing request fields, configuration keys, or test fixtures." },
      { title: "Editorial headings", text: "Create a sentence-case or title-case starting point for headings, then restore brand names and domain-specific capitalization manually." },
      { title: "File and URL slugs", text: "Turn a phrase into a kebab-style value before applying the additional transliteration and reserved-word rules of a real slug system." },
    ],
    review: "Automatic word detection is heuristic. Check acronyms, initialisms, product spelling, apostrophes, numbers, and words from languages whose capitalization rules differ from English.",
    alternative: "Use a project-specific naming library when identifiers must follow a formal schema, locale-aware title rules, transliteration policy, or reserved-key list. This tool provides a reviewable first pass.",
    privacy: "Text is transformed locally. Identifiers can still disclose internal project names or customer information when copied into tickets, screenshots, and public repositories.",
    checklist: ["Restore acronyms and proper nouns.", "Check leading numbers and punctuation.", "Follow the destination style guide.", "Validate generated API keys against the schema."],
    relatedGuides: [],
  },
  "line-processor": {
    scenarios: [
      { title: "Keyword and URL lists", text: "Trim, deduplicate, and sort copied lists before importing them into a spreadsheet, campaign, allowlist, or review document." },
      { title: "Batch command preparation", text: "Add a controlled prefix or suffix to every line, then inspect the result before using it as input to another tool." },
      { title: "Data reconciliation", text: "Normalize casing and empty rows to compare two one-item-per-line exports without writing a temporary script." },
    ],
    review: "Operation order changes the answer. For example, case-sensitive deduplication before lowercasing keeps entries that would collapse if the same actions were reversed.",
    alternative: "Use a spreadsheet or data-processing language for multi-column records, quoted CSV, relational joins, or transformations that must be repeated and audited as one pipeline.",
    privacy: "Lists never need to be uploaded to 77 Toolkit, but copied exports may contain email addresses, private URLs, or account IDs. Replace sensitive values before sharing output.",
    checklist: ["Choose operation order before starting.", "Confirm case-sensitive behavior.", "Preserve a copy of the source list.", "Spot-check the first and last results."],
    relatedGuides: [],
  },
  "word-counter": {
    scenarios: [
      { title: "Publishing limits", text: "Measure words and characters before submitting an abstract, listing, form response, or social post with a documented limit." },
      { title: "Reading estimate", text: "Use sentence and word totals to estimate the scale of a draft while remembering that audience and technical density affect actual reading time." },
      { title: "Repetition review", text: "Inspect frequent terms to notice accidental repetition, missing terminology, or copied boilerplate before a manual editorial pass." },
    ],
    review: "Counting conventions differ for hyphenated terms, contractions, emoji, CJK text, and URLs. Compare the destination platform's own counter when a hard publishing limit has contractual consequences.",
    alternative: "Use a language-specific editor for readability scoring, grammar, citations, or editorial quality. Counts describe surface structure and cannot determine whether writing is accurate or useful.",
    privacy: "Analysis runs locally and no document history is created by the site. The browser, clipboard, and device may still retain content according to their own policies.",
    checklist: ["Identify words or characters as the real limit.", "Check whether spaces count.", "Compare the destination platform counter.", "Use frequency results as prompts, not quality scores."],
    relatedGuides: [],
  },
  "markdown-preview": {
    scenarios: [
      { title: "README drafting", text: "Preview headings, lists, links, quotations, and code while drafting a short project note without uploading an unpublished repository description." },
      { title: "CMS handoff", text: "Inspect the HTML shape produced by a bounded Markdown subset before placing reviewed content into a system with its own sanitizer." },
      { title: "Unsafe sample review", text: "Demonstrate that pasted tags remain text in this preview while discussing why raw HTML support requires a maintained sanitization policy." },
    ],
    review: "Compare the result in the destination Markdown engine. Pay special attention to blank lines, nested lists, underscores inside words, link destinations, raw HTML, code fences, and features this subset intentionally leaves unsupported.",
    alternative: "Use a maintained CommonMark or GitHub Flavored Markdown parser together with a well-configured HTML sanitizer when exact dialect compatibility, plugins, tables, task lists, or untrusted production content are required.",
    privacy: "Draft text and generated nodes remain in the tab. Documents can contain unpublished plans, internal links, credentials in code blocks, or personal information, so remove secrets before sharing previews or copied HTML.",
    checklist: ["Confirm the destination dialect.", "Review every link target.", "Keep raw HTML disabled for untrusted input.", "Sanitize again at the production boundary."],
    relatedGuides: [],
  },
  "color-spectrum": {
    scenarios: [
      { title: "Brand exploration", text: "Extract dominant colors from an approved image to create a starting palette for a presentation, campaign, or interface concept." },
      { title: "Asset QA", text: "Inspect individual pixels and color proportions when an exported graphic looks different from the expected background or accent colors." },
      { title: "Creative handoff", text: "Export a compact palette reference so designers and developers can discuss exact hexadecimal values instead of subjective color names." },
    ],
    review: "Dominant-color extraction is a summary, not a color-management system. Gradients, transparency, color profiles, compression artifacts, and very small accents can change the palette or be underrepresented.",
    alternative: "Use a calibrated design or photo application when print production, ICC profiles, wide-gamut color, spot colors, or pixel-perfect professional sampling is required.",
    privacy: "The selected image is decoded locally. The resulting palette usually reveals little, but screenshots and exported previews can still disclose the source image or project context.",
    checklist: ["Preview the full image first.", "Sample small accents manually.", "Check colors on the target display space.", "Run contrast tests before using text colors."],
    relatedGuides: ["image-formats-and-compression", "wcag-color-contrast"],
  },
  "image-compressor": {
    scenarios: [
      { title: "Website delivery", text: "Reduce a photograph before publishing it to improve transfer size while comparing visible detail at the actual display dimensions." },
      { title: "Email and chat", text: "Create a smaller copy that fits an attachment limit without overwriting the high-quality source file." },
      { title: "CMS preparation", text: "Test JPEG or WebP quality levels locally before uploading an asset into a content system that may apply another compression pass." },
    ],
    review: "Compare file size and image quality at 100 percent zoom and at the intended display size. Watch text, line art, gradients, transparency, and already-compressed images for disproportionate damage.",
    alternative: "Resize first when pixel dimensions are much larger than the destination. Use a professional optimizer for animated formats, lossless tuning, metadata policy, or repeatable build-pipeline output.",
    privacy: "Encoding happens in browser memory and the source is not sent to a 77 Toolkit server. Keep the original because re-encoding is normally lossy and cannot restore discarded detail.",
    checklist: ["Preserve the original file.", "Resize oversized images before quality tuning.", "Compare at the final display size.", "Avoid repeated lossy re-encoding."],
    relatedGuides: ["image-formats-and-compression"],
  },
  "image-resizer": {
    scenarios: [
      { title: "Responsive assets", text: "Create a smaller raster image close to its rendered width instead of asking every visitor to download unused pixels." },
      { title: "Platform requirements", text: "Fit an avatar, listing image, or presentation asset to a documented width and height while preserving the original separately." },
      { title: "Prototype preparation", text: "Produce predictable dimensions for a mockup or test dataset without uploading private source artwork to a conversion service." },
    ],
    review: "Check aspect ratio, orientation, sharpness, transparency, and export format. Stretching changes geometry, while cropping and padding are different operations that this simple resizer does not infer automatically.",
    alternative: "Use a crop tool when composition must change, an art-directed editor when focal points matter, or a build pipeline when multiple responsive sizes must be generated consistently.",
    privacy: "The browser reads and redraws the image locally. Re-encoding can remove some metadata, but metadata removal should not be assumed unless the dedicated workflow is used and verified.",
    checklist: ["Lock aspect ratio unless stretching is intended.", "Choose dimensions for the real destination.", "Inspect transparency after export.", "Never replace the only source copy."],
    relatedGuides: ["image-formats-and-compression"],
  },
  "image-converter": {
    scenarios: [
      { title: "Web compatibility", text: "Convert a supported source into PNG, JPEG, or WebP when the receiving browser, CMS, or API requires a different raster format." },
      { title: "Transparency decisions", text: "Move artwork to PNG or WebP when alpha transparency is needed, or choose JPEG when a flat photographic output is acceptable." },
      { title: "File-size testing", text: "Export the same visual in multiple formats and compare size and quality rather than assuming one format is universally smaller." },
    ],
    review: "Look for lost transparency, matte backgrounds, color shifts, text artifacts, animation loss, and a larger output than the source. Conversion changes encoding; it does not improve low-quality pixels.",
    alternative: "Use a specialized application for SVG, HEIC, RAW, animated GIF/WebP, ICC profile preservation, or batch conversion with controlled metadata and color management.",
    privacy: "Conversion uses Canvas and browser encoders locally. The export is a new file, so retain the source and verify that the new format meets the destination's quality and metadata requirements.",
    checklist: ["Choose a format for content type.", "Confirm transparency behavior.", "Compare size and visible quality.", "Check whether animation must be preserved."],
    relatedGuides: ["image-formats-and-compression"],
  },
  "contrast-checker": {
    scenarios: [
      { title: "Design review", text: "Check proposed text and background colors before a component is implemented, including normal, hover, disabled, and focus states." },
      { title: "Accessibility QA", text: "Reproduce a reported contrast problem with exact color values and compare the ratio with the relevant WCAG text target." },
      { title: "Palette adjustment", text: "Explore nearby foreground or background values while preserving brand intent and keeping the result readable in the real interface." },
    ],
    review: "Select the correct criterion for text size and weight, and test the colors that are actually composited on screen. Opacity, gradients, images, antialiasing, and state changes can alter effective contrast.",
    alternative: "Use an accessibility audit in the rendered product for full-page checks, keyboard behavior, semantics, focus visibility, zoom, motion, and non-text contrast. A ratio is only one requirement.",
    privacy: "Color values contain no uploaded document, and calculation is local. Screenshots used to obtain colors may still include confidential UI or customer information.",
    checklist: ["Use the final composited colors.", "Check every interactive state.", "Confirm text size and weight.", "Test the implemented component, not only the palette."],
    relatedGuides: ["wcag-color-contrast"],
  },
  "metadata-remover": {
    scenarios: [
      { title: "Public sharing", text: "Create a new copy of a personal photo before posting it where camera details, timestamps, or embedded location data are unnecessary." },
      { title: "Support attachments", text: "Remove common image metadata before attaching a screenshot or photo to a public issue, while also reviewing visible private information." },
      { title: "Content publishing", text: "Standardize a web-ready raster export that does not intentionally carry the source application's EXIF or editing metadata." },
    ],
    review: "Download the result and inspect it with an independent metadata viewer. Also examine the visible pixels, filename, surrounding message, cloud-sharing link, and platform behavior because privacy exposure is not limited to EXIF.",
    alternative: "Use a forensic or format-specific metadata tool when legal evidence, complete container inspection, color-profile preservation, animation, or uncommon metadata blocks must be handled predictably.",
    privacy: "The image is re-encoded locally, so the source file is not uploaded to 77 Toolkit. Re-encoding is a practical privacy step, not a guarantee that every possible hidden payload or visible clue is removed.",
    checklist: ["Keep the untouched original privately.", "Inspect the result with another viewer.", "Review visible faces, screens, and addresses.", "Rename the file before public sharing when needed."],
    relatedGuides: ["removing-image-metadata", "image-formats-and-compression"],
  },
  "url-parser": {
    scenarios: [
      { title: "Redirect debugging", text: "Separate a redirect target into origin, path, query, and fragment before deciding whether an unexpected destination came from routing or one parameter." },
      { title: "OAuth callback review", text: "Inspect callback and state parameters without visiting the URL, while treating authorization codes and session values as credentials that should be redacted." },
      { title: "Tracking-link cleanup", text: "Identify repeated campaign parameters and distinguish them from values that the destination application actually requires." },
    ],
    review: "Read the hostname from right to left, check the effective port and scheme, and look for credentials, punycode, misleading subdomains, encoded separators, repeated parameters, and fragments that may alter client-side behavior.",
    alternative: "Use browser developer tools or a network inspector when the task is to follow redirects, observe DNS and TLS, or inspect an actual HTTP response. This tool intentionally performs no remote request.",
    privacy: "Parsing stays local, but copied URLs can contain email addresses, document IDs, reset tokens, authorization codes, analytics identifiers, and internal hostnames. Redact those values before sharing a screenshot or bug report.",
    checklist: ["Confirm the complete hostname.", "Review repeated query keys in order.", "Treat credentials and tokens as secrets.", "Do not infer safety from valid syntax."],
    relatedGuides: ["url-encoding-and-query-parameters"],
  },
  "url-encoder": {
    scenarios: [
      { title: "Query parameter values", text: "Encode a search phrase, callback URL, filename, or filter value before adding it to a query string without turning its data into new separators." },
      { title: "API troubleshooting", text: "Decode one suspicious value to check for spaces, Unicode text, nested URLs, or double encoding while reproducing a request." },
      { title: "Path-segment preparation", text: "Encode user-provided segment data separately before combining it with the fixed slash structure controlled by an application." },
    ],
    review: "Confirm what layer is being encoded. A full URL nested inside a query value needs component encoding, while encoding an already encoded value can create percent signs that survive one decode and change behavior later.",
    alternative: "Use the URL and URLSearchParams APIs in application code when constructing a complete address. They express structure directly and avoid brittle string concatenation around ampersands, equals signs, and question marks.",
    privacy: "Encoding and decoding are local. The readable result may expose sensitive content that was visually obscured by percent sequences, so handle decoded URLs with the same care as the original credentials or identifiers.",
    checklist: ["Choose component or full-URI mode.", "Avoid accidental double encoding.", "Check Unicode after decoding.", "Construct production URLs with URL APIs."],
    relatedGuides: ["url-encoding-and-query-parameters"],
  },
  "csv-json-converter": {
    scenarios: [
      { title: "Small data handoff", text: "Turn a reviewed spreadsheet export into JSON fixtures for a prototype without installing a desktop converter or uploading customer rows." },
      { title: "API export preparation", text: "Convert a flat JSON response into CSV for a colleague who needs filtering and review in a spreadsheet." },
      { title: "CSV dialect diagnosis", text: "Test whether a delimiter, quoted newline, or escaped quotation mark explains why an import created the wrong number of columns." },
    ],
    review: "Compare input and output row counts, inspect the longest and emptiest records, and protect identifiers such as postal codes or account numbers from automatic numeric conversion in the destination spreadsheet.",
    alternative: "Use a dedicated data pipeline for large files, streaming conversion, schema validation, character-set conversion, nested normalization, or repeatable business transformations. This browser tool is for small, reviewable datasets.",
    privacy: "The source remains in the tab, but CSV exports often contain names, email addresses, transaction data, or formulas. Use synthetic examples for public reports and clear the page when working on a shared device.",
    checklist: ["Choose the real delimiter.", "Compare row and column counts.", "Keep identifiers as text.", "Inspect formulas before spreadsheet import."],
    relatedGuides: [],
  },
  "html-entities": {
    scenarios: [
      { title: "Documentation examples", text: "Encode angle brackets so a tutorial or CMS displays an HTML snippet literally instead of interpreting it as document structure." },
      { title: "Template debugging", text: "Decode a short value to determine whether one or two escaping layers produced visible ampersands or entity names in rendered output." },
      { title: "Content migration", text: "Review encoded headings or descriptions before moving them between systems that disagree about whether input is plain text or HTML." },
    ],
    review: "Identify the destination context before using the output. HTML element text, quoted attributes, unquoted attributes, URLs, CSS, and JavaScript strings do not share one universal escaping rule.",
    alternative: "Use automatic contextual escaping from a maintained template framework and a proven sanitizer for user-authored markup. Manual entity conversion is appropriate for inspection, not as an application's complete XSS defense.",
    privacy: "Conversion happens locally. Decoded text can reveal hidden markup, links, or identifiers, but the tool never treats that result as executable HTML in its own interface.",
    checklist: ["Name the destination context.", "Encode before interpolation.", "Sanitize allowed markup separately.", "Test the final rendered page."],
    relatedGuides: ["url-encoding-and-query-parameters"],
  },
  "css-unit-converter": {
    scenarios: [
      { title: "Design handoff", text: "Translate a pixel measurement into rem using the actual root font assumption recorded in a design system." },
      { title: "Responsive debugging", text: "Compare a vw or vh measurement with its pixel result at a reported viewport size before reproducing a layout issue." },
      { title: "Typography review", text: "Check how an em-based spacing or component value relates to both the element font size and the document root." },
    ],
    review: "Verify the real computed root and element font sizes, viewport dimensions, browser zoom, and minimum or maximum constraints. A mathematically equivalent value can behave differently once it participates in the CSS cascade and layout.",
    alternative: "Use browser developer tools for computed styles and a real responsive test matrix for production decisions. Use clamp, container units, design tokens, or media queries when a value needs controlled behavior rather than direct equivalence.",
    privacy: "The calculator receives only numeric layout assumptions and does not inspect a page or fetch a stylesheet. Project-specific dimensions can still reveal internal design tokens when copied into public examples.",
    checklist: ["Record root and element font sizes.", "Use the target viewport dimensions.", "Test zoom and text scaling.", "Verify min/max constraints in context."],
    relatedGuides: ["wcag-color-contrast"],
  },
};
